name: ibp
channels:
  - pytorch
  - nvidia/label/cuda-11.7.0
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_14
  - alsa-lib=1.2.8=h166bdaf_0
  - aria2=1.36.0=h319415d_2
  - atk-1.0=2.36.0=h3371d22_4
  - attr=2.5.1=h166bdaf_1
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - blas=2.121=mkl
  - blas-devel=3.9.0=21_linux64_mkl
  - boost=1.82.0=h8003fee_2
  - brotli-python=1.1.0=py39hf88036b_2
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=h35add3b_1015
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cmake=3.25.2=h077f3f9_0
  - cpython=3.9.22=py39hd8ed1ab_1
  - cuda-cccl=11.7.58=hc415cf5_0
  - cuda-command-line-tools=11.7.0=0
  - cuda-compiler=11.7.0=0
  - cuda-cudart=11.7.60=h9538e0e_0
  - cuda-cudart-dev=11.7.60=h6a7c232_0
  - cuda-cuobjdump=11.7.50=h28cc80a_0
  - cuda-cupti=11.7.50=hb6f9eaf_0
  - cuda-cuxxfilt=11.7.50=hb365495_0
  - cuda-documentation=11.7.50=0
  - cuda-driver-dev=11.7.60=0
  - cuda-gdb=11.7.50=h4a0ac72_0
  - cuda-libraries=11.7.0=0
  - cuda-libraries-dev=11.7.0=0
  - cuda-memcheck=11.7.50=hc446b2b_0
  - cuda-nsight=11.7.50=0
  - cuda-nsight-compute=11.7.0=0
  - cuda-nvcc=11.7.64=0
  - cuda-nvdisasm=11.7.50=h5bd0695_0
  - cuda-nvml-dev=11.7.50=h3af1343_0
  - cuda-nvprof=11.7.50=h7a2404d_0
  - cuda-nvprune=11.7.50=h7add7b4_0
  - cuda-nvrtc=11.7.50=hd0285e0_0
  - cuda-nvrtc-dev=11.7.50=heada363_0
  - cuda-nvtx=11.7.50=h05b0816_0
  - cuda-nvvp=11.7.50=hd2289d5_0
  - cuda-runtime=11.7.0=0
  - cuda-sanitizer-api=11.7.50=hb424887_0
  - cuda-toolkit=11.7.0=0
  - cuda-tools=11.7.0=0
  - cuda-version=11.7=h67201e3_2
  - cuda-visual-tools=11.7.0=0
  - cudatoolkit=11.7.1=h4bc3d14_13
  - cudnn=8.8.0.121=hcdd5f01_4
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc=10.4.0=hb92f740_13
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - gcc_linux-64=10.4.0=h9215b83_13
  - gdb=14.2=py39h1a87753_0
  - gdk-pixbuf=2.42.10=h05c8ddd_0
  - gds-tools=1.3.0.44=0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.2.1=py39h7196dd7_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.49.1=h85b4f2f_0
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - gxx=10.4.0=hb92f740_13
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - gxx_linux-64=10.4.0=h6e491c6_13
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=6.0.0=h3ff4399_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - htop=3.3.0=h2475386_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.10=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - kernel-headers_linux-64=3.10.0=h4a8ded7_14
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=21_linux64_mkl
  - libboost=1.82.0=h1bacd13_2
  - libboost-devel=1.82.0=h00ab1b0_2
  - libboost-headers=1.82.0=ha770c72_2
  - libboost-python=1.82.0=py39hda80f44_2
  - libboost-python-devel=1.82.0=py39h8003fee_2
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=21_linux64_mkl
  - libcbor=0.9.0=h9c3ff4c_0
  - libcublas=11.10.1.25=he442b6f_0
  - libcublas-dev=11.10.1.25=h0c8ac2b_0
  - libcufft=10.7.2.50=h80a1efe_0
  - libcufft-dev=10.7.2.50=h59a5ac8_0
  - libcufile=1.3.0.44=0
  - libcufile-dev=1.3.0.44=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.2.10.50=heec50f7_0
  - libcurand-dev=10.2.10.50=hd49a9cd_0
  - libcurl=7.87.0=h6312ad2_0
  - libcusolver=11.3.5.50=hcab339c_0
  - libcusolver-dev=11.3.5.50=hc6eba6f_0
  - libcusparse=11.7.3.50=h6aaafad_0
  - libcusparse-dev=11.7.3.50=hc644b96_0
  - libdeflate=1.14=h166bdaf_0
  - libdrm-cos7-x86_64=2.4.97=h9b0a68f_1105
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.6=h2dba641_1
  - libfido2=1.11.0=h727a467_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=14.2.0=h69a702a_2
  - libgd=2.3.3=h8faadc7_5
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.80.2=hf974151_0
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.7.1=h32351e8_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=21_linux64_mkl
  - liblapacke=3.9.0=21_linux64_mkl
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnl=3.9.0=hd590300_0
  - libnpp=11.7.3.21=h3effbd9_0
  - libnpp-dev=11.7.3.21=hb6476a9_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libnvjpeg=11.7.2.34=hfe236c7_0
  - libnvjpeg-dev=11.7.2.34=h2e48410_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.21.12=hfc55251_2
  - librsvg=2.52.2=hc3c00ef_0
  - libsanitizer=10.4.0=h5246dfb_19
  - libsqlite=3.45.1=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.0=h82bc61c_0
  - libtool=2.4.7=he02047a_1
  - libudev1=255=h3f72095_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.11.5=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - lightning-utilities=0.14.3=pyhd8ed1ab_0
  - llvm-openmp=19.1.0=h84d6215_0
  - magma=2.6.2=hc72dce7_0
  - markupsafe=3.0.2=py39h9399b63_1
  - mesa-libegl-cos7-x86_64=18.3.4=h9b0a68f_1105
  - mesa-libgbm-cos7-x86_64=18.3.4=h9b0a68f_1105
  - mesa-libglapi-cos7-x86_64=18.3.4=h9b0a68f_1105
  - mkl=2024.0.0=ha957f24_49657
  - mkl-devel=2024.0.0=ha770c72_49657
  - mkl-include=2024.0.0=ha957f24_49657
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h9458935_0
  - mpi=1.0=openmpi
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nccl=2.23.4.1=h03a54cd_0
  - ncurses=6.4=h59595ed_2
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nsight-compute=2022.2.0.13=0
  - numactl=2.0.16=h0b41bf4_1
  - numpy=1.26.4=py39h474f0d3_0
  - nvcomp=3.0.6=h56904bc_0
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openh264=2.1.1=h780b84a_0
  - openjdk=17.0.3=h58dac75_5
  - openjpeg=2.5.0=hfec8fc6_2
  - openmpi=4.1.4=ha1ae619_102
  - openmpi-mpicc=4.1.4=h166bdaf_102
  - openmpi-mpicxx=4.1.4=h924138e_102
  - openssh=9.1p1=h2baec63_1
  - openssl=1.1.1w=hd590300_0
  - pandoc=3.1.12.1=ha770c72_0
  - pango=1.50.14=hd33c08f_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.43=hcad00b1_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pygraphviz=1.9=py39ha206bd0_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=h47a2c10_0_cpython
  - python_abi=3.9=6_cp39
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - rhash=1.4.3=hd590300_2
  - setuptools=69.1.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.7=h1b44611_0
  - sqlite=3.45.1=h2c6b66d_0
  - sysroot_linux-64=2.17=h4a8ded7_14
  - tbb=2021.7.0=h924138e_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=0.13.1=py39_cu117
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - blis==1.2.1
      - bottle==0.12.25
      - catalogue==2.0.10
      - cattrs==22.2.0
      - cfgv==3.4.0
      - click==8.1.8
      - cloudpathlib==0.21.0
      - confection==0.1.5
      - contexttimer==0.3.3
      - contourpy==1.3.0
      - cryptography==44.0.3
      - cuda-bindings==12.9.0
      - cuda-python==12.9.0
      - cycler==0.12.1
      - cymem==2.0.11
      - dacite==1.9.2
      - datasets==2.21.0
      - decorator==5.2.1
      - deprecated==1.2.18
      - diffusers==0.29.0
      - dill==0.3.8
      - distlib==0.3.9
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - fabric==3.2.2
      - fastapi==0.115.12
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - google==3.0.0
      - h11==0.16.0
      - huggingface-hub==0.30.2
      - identify==2.6.10
      - importlib-metadata==8.7.0
      - importlib-resources==5.13.0
      - invoke==2.2.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - mako==1.3.10
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - msgpack==1.1.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - ninja==1.11.1.4
      - nltk==3.9.1
      - nodeenv==1.9.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-ml-py==12.575.51
      - packaging==24.2
      - pandas==2.2.3
      - parameterized==0.9.0
      - paramiko==3.5.1
      - platformdirs==4.3.8
      - plumbum==1.9.0
      - portalocker==3.1.1
      - pre-commit==4.2.0
      - preshed==3.0.9
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pulp==3.1.1
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.6
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyhocon==0.3.61
      - pynacl==1.5.0
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.46.0
      - referencing==0.36.2
      - regex==2024.11.6
      - retrying==1.3.4
      - rich==14.0.0
      - rouge-score==0.1.2
      - rpds-py==0.24.0
      - rpyc==6.0.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - spacy==3.8.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlitedict==2.1.0
      - srsly==2.5.1
      - starlette==0.46.2
      - sympy==1.14.0
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - tokenizers==0.15.2
      - torch==1.13.1
      - torchdata==0.5.1
      - torchmetrics==0.11.1
      - tqdm==4.67.1
      - transformers==4.24
      - typer==0.15.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uncertainty-calibration==0.1.4
      - uvicorn==0.29.0
      - virtualenv==20.31.2
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.21.0
      - zstandard==0.18.0